# Generated by Django 3.2 on 2021-04-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Favorite Book Genre',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_book_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book_genre',
            field=models.ManyToManyField(blank=True, to='users.FavoriteBookGenre'),
        ),
    ]
